imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: true
h4cc_alice_fixtures:

    default_manager:  orm

    managers:

        orm:
            # Locale which will be used by faker for randomized data.
            locale:               en_EN

            # A seed to make sure Faker generates data consistently across runs, set to "null" to disable.
            seed:                 1

            # Set to false if no ORM flushes should be made.
            do_flush:             true

            # Define service id for the used Schema tool.
            #schema_tool:          null
            schema_tool:          null
            #object_manager:          null

            # This option enables selecting between Doctrine ORM and MongoDB ODM and will set the default object_manager and schema_tool services.
            doctrine:             "orm" # One of "orm"; "mongodb-odm"